// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-skills.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-skills.ts
var list_skills_default = defineTool({
  name: "list_skills",
  title: "List skills",
  description: "List skill listings offered by students, newest first. Optionally filter by category.",
  inputSchema: {
    category: z.string().trim().optional().describe("Category to filter by, e.g. 'Web Development'."),
    limit: z.number().int().optional().describe("Max number of listings to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("skills").select("id, title, category, description, experience, hourly_rate, availability, created_at, user_id").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.ilike("category", `%${category}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const userIds = [...new Set((data ?? []).map((s) => s.user_id))];
    let profileMap = /* @__PURE__ */ new Map();
    if (userIds.length > 0) {
      const { data: profiles } = await supabase.from("profiles").select("user_id, full_name, department").in("user_id", userIds);
      profileMap = new Map((profiles ?? []).map((p) => [p.user_id, p]));
    }
    const skills = (data ?? []).map((s) => ({
      ...s,
      owner: profileMap.get(s.user_id) ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(skills) }],
      structuredContent: { skills }
    };
  }
});

// src/lib/mcp/tools/search-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var search_skills_default = defineTool2({
  name: "search_skills",
  title: "Search skills",
  description: "Search skill listings by keyword across title, description, and category.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Keyword to search for, e.g. 'react' or 'photography'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,()]/g, " ");
    const { data, error } = await supabase.from("skills").select("id, title, category, description, experience, hourly_rate, availability, user_id").or(`title.ilike.%${escaped}%,description.ilike.%${escaped}%,category.ilike.%${escaped}%`).order("created_at", { ascending: false }).limit(20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { skills: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-skill.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var get_skill_default = defineTool3({
  name: "get_skill",
  title: "Get skill details",
  description: "Get a single skill listing by ID, including the owner's profile and its reviews.",
  inputSchema: {
    id: z3.string().trim().min(1).describe("The skill listing ID (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: skill, error } = await supabase.from("skills").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!skill) throw new ToolError(`No skill found with id ${id}`);
    const [{ data: owner }, { data: reviews }] = await Promise.all([
      supabase.from("profiles").select("user_id, full_name, department, academic_year, avatar_url, bio").eq("user_id", skill.user_id).maybeSingle(),
      supabase.from("reviews").select("id, rating, comment, created_at, user_id").eq("target_id", id).eq("target_type", "skill").order("created_at", { ascending: false })
    ]);
    const result = { skill, owner: owner ?? null, reviews: reviews ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-activities.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_activities_default = defineTool4({
  name: "list_activities",
  title: "List activities",
  description: "List campus activities and events, newest first. Optionally filter by category.",
  inputSchema: {
    category: z4.string().trim().optional().describe("Category to filter by, e.g. 'Workshop'."),
    limit: z4.number().int().optional().describe("Max number of activities to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("activities").select("id, title, category, description, date, time, venue, max_participants, requirements, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.ilike("category", `%${category}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { activities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's profile, including name, department, and academic year.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("user_id, full_name, email, department, academic_year, bio, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError2("Profile not found for the signed-in user");
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/create-skill.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var create_skill_default = defineTool6({
  name: "create_skill",
  title: "Create skill listing",
  description: "Create a new skill listing offered by the signed-in user.",
  inputSchema: {
    title: z5.string().trim().min(1).describe("Skill title, e.g. 'React tutoring'."),
    category: z5.string().trim().min(1).describe("Skill category, e.g. 'Web Development'."),
    description: z5.string().trim().optional().describe("What the user offers and for whom."),
    experience: z5.string().trim().optional().describe("Experience level, e.g. 'Intermediate'."),
    hourly_rate: z5.string().trim().optional().describe("Hourly rate as text, e.g. '200' for \u20B9200/hr."),
    availability: z5.string().trim().optional().describe("Availability, e.g. 'Weekends'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, category, description, experience, hourly_rate, availability }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("skills").insert({
      user_id: ctx.getUserId(),
      title,
      category,
      description: description ?? null,
      experience: experience ?? null,
      hourly_rate: hourly_rate ?? null,
      availability: availability ?? null
    }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { skill: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "amuzfybqeoszyjvxzbpz";
var mcp_default = defineMcp({
  name: "skill-spark-collective-03",
  title: "skill-spark-collective-03",
  version: "0.1.0",
  instructions: "Tools for GTA, the RNSIT campus skill-sharing app. Use list_skills/search_skills/get_skill to browse student skill listings, list_activities for campus events, get_my_profile for the signed-in user, and create_skill to publish a new listing.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_skills_default,
    search_skills_default,
    get_skill_default,
    list_activities_default,
    get_my_profile_default,
    create_skill_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
